USE [master]
GO

/****** Object:  Database [OnlineShop]    Script Date: 6/27/2018 6:37:42 AM ******/
CREATE DATABASE [OnlineShop]
GO

ALTER DATABASE [OnlineShop] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnlineShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnlineShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnlineShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnlineShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnlineShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OnlineShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnlineShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnlineShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnlineShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnlineShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnlineShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnlineShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnlineShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnlineShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OnlineShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnlineShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnlineShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnlineShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnlineShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnlineShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OnlineShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnlineShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OnlineShop] SET  MULTI_USER 
GO

ALTER DATABASE [OnlineShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnlineShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnlineShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnlineShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OnlineShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnlineShop] SET QUERY_STORE = OFF
GO

USE [OnlineShop]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OnlineShop] SET  READ_WRITE 
GO

